<?php

declare(strict_types=1);

use MB\BitrixTest\Bootstrap\PrologBootstrap;
use MB\BitrixTest\Install\InstalledCore;

$autoloadCandidates = [
    (getcwd() ?: '') . '/vendor/autoload.php',
    dirname(__DIR__, 2) . '/vendor/autoload.php',
];
$autoloadLoaded = false;
foreach ($autoloadCandidates as $autoloadPath) {
    if (is_file($autoloadPath)) {
        require_once $autoloadPath;
        $autoloadLoaded = true;
        break;
    }
}
if (! $autoloadLoaded) {
    throw new RuntimeException('Composer autoload.php not found.');
}

$projectRoot = dirname(__DIR__, 2);
$schemaDir = $projectRoot . '/resources/schema';
$runtimeRoot = $projectRoot . '/.runtime/dump-build';
$baseDbPath = $runtimeRoot . '/base.sqlite';
$shopDbPath = $runtimeRoot . '/shop.sqlite';

if (! is_dir($schemaDir)) {
    mkdir($schemaDir, 0777, true);
}
if (! is_dir($runtimeRoot)) {
    mkdir($runtimeRoot, 0777, true);
}

$corePath = InstalledCore::path();
if (! is_dir($corePath . '/modules/main')) {
    throw new RuntimeException('Bitrix core is not installed: ' . $corePath);
}

buildDatabase(
    $corePath,
    $runtimeRoot,
    $baseDbPath,
    'base',
    false
);
dumpSqliteDatabase($baseDbPath, $schemaDir . '/sqlite-base.sql');

buildDatabase(
    $corePath,
    $runtimeRoot,
    $shopDbPath,
    'shop',
    true
);
dumpSqliteDatabase($shopDbPath, $schemaDir . '/sqlite-shop.sql');

echo "Generated:\n";
echo " - " . $schemaDir . "/sqlite-base.sql\n";
echo " - " . $schemaDir . "/sqlite-shop.sql\n";

function buildDatabase(
    string $corePath,
    string $runtimeRoot,
    string $sqlitePath,
    string $mode,
    bool $importShopXml
): void {
    if (is_file($sqlitePath)) {
        unlink($sqlitePath);
    }

    PrologBootstrap::reset();
    putenv('BITRIX_BOOTSTRAP_MODE=full');
    putenv('BITRIX_USE_SQLITE=1');
    putenv('BITRIX_RUNTIME_ROOT=' . $runtimeRoot);
    putenv('BITRIX_SQLITE_MODE=' . $mode);
    putenv('BITRIX_SQLITE_IMPORT_CORE_INSTALL_SQL=1');
    putenv('BITRIX_SQLITE_IMPORT_CORE_SHOP_DEMO_SQL=' . ($importShopXml ? '1' : '0'));
    putenv('BITRIX_IMPORT_ESHOP_DEMO_XML=' . ($importShopXml ? '1' : '0'));
    putenv('BITRIX_ESHOP_LOCALIZATION=ru');

    PrologBootstrap::boot([
        'core_path' => $corePath,
        'runtime_root' => $runtimeRoot,
        'sqlite_path' => $sqlitePath,
        'sqlite' => true,
        'sqlite_mode' => $mode,
        'sqlite_import_core_install_sql' => true,
        'sqlite_import_core_shop_demo_sql' => $importShopXml,
        'eshop_import_demo_xml' => $importShopXml,
    ]);
}

function dumpSqliteDatabase(string $sqlitePath, string $outputPath): void
{
    $pdo = new PDO('sqlite:' . $sqlitePath, null, null, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);

    $lines = [];
    $lines[] = '-- Generated by scripts/sqlite/generate-dumps.php';
    $lines[] = 'PRAGMA foreign_keys=OFF;';
    $lines[] = 'BEGIN TRANSACTION;';

    $schemaRows = $pdo->query(
        "SELECT type, name, tbl_name, sql
         FROM sqlite_master
         WHERE sql IS NOT NULL
           AND name NOT LIKE 'sqlite_%'
         ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'index' THEN 1 WHEN 'trigger' THEN 2 ELSE 3 END, name"
    )->fetchAll(PDO::FETCH_ASSOC);

    foreach ($schemaRows as $row) {
        $sql = trim((string) $row['sql']);
        if ($sql === '') {
            continue;
        }
        $lines[] = $sql . ';';
    }

    $tables = $pdo->query(
        "SELECT name
         FROM sqlite_master
         WHERE type='table'
           AND name NOT LIKE 'sqlite_%'
         ORDER BY name"
    )->fetchAll(PDO::FETCH_COLUMN);

    foreach ($tables as $tableName) {
        $quotedTable = '"' . str_replace('"', '""', (string) $tableName) . '"';
        $rows = $pdo->query('SELECT * FROM ' . $quotedTable)->fetchAll(PDO::FETCH_ASSOC);
        foreach ($rows as $row) {
            $columns = array_map(
                static fn (string $column): string => '"' . str_replace('"', '""', $column) . '"',
                array_keys($row)
            );
            $values = array_map(static fn (mixed $value): string => sqliteValue($value), array_values($row));
            $lines[] = 'INSERT INTO ' . $quotedTable . ' (' . implode(', ', $columns) . ') VALUES (' . implode(', ', $values) . ');';
        }
    }

    $lines[] = 'COMMIT;';
    file_put_contents($outputPath, implode(PHP_EOL, $lines) . PHP_EOL);
}

function sqliteValue(mixed $value): string
{
    if ($value === null) {
        return 'NULL';
    }
    if (is_int($value) || is_float($value)) {
        return (string) $value;
    }

    return "'" . str_replace("'", "''", (string) $value) . "'";
}
