-- Generated by scripts/sqlite/generate-dumps.php
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE b_adv_banner_2_country
(
	BANNER_ID int(18) not null default '0',
	COUNTRY_ID char(2) not null,
	REGION varchar(200),
	CITY_ID int(18)
);
CREATE TABLE b_adv_banner_2_day
(
	DATE_STAT date not null,
	BANNER_ID int(18) not null default '0',
	SHOW_COUNT int(18) not null default '0',
	CLICK_COUNT int(18) not null default '0',
	VISITOR_COUNT int(18) not null default '0',
	primary key (BANNER_ID, DATE_STAT)
);
CREATE TABLE b_adv_banner_2_group
(
  	BANNER_ID int(18) not null default '0',
	GROUP_ID int(18) not null default '0',
	primary key(BANNER_ID, GROUP_ID)
);
CREATE TABLE b_adv_banner_2_site
(
	BANNER_ID int(18) not null default '0',
	SITE_ID char(2) not null,
	primary key (BANNER_ID, SITE_ID)
);
CREATE TABLE b_adv_banner_2_stat_adv
(
	BANNER_ID int(18) not null default '0',
	STAT_ADV_ID int(18) not null default '0',
	primary key (BANNER_ID, STAT_ADV_ID)
);
CREATE TABLE b_adv_banner_2_weekday
(
	BANNER_ID int(18) not null default '0',
	C_WEEKDAY varchar(10) not null,
	C_HOUR int(2) not null default '0',
	primary key (BANNER_ID, C_WEEKDAY, C_HOUR)
);
CREATE TABLE b_adv_contract_2_site
(
	CONTRACT_ID int(18) not null default '0',
	SITE_ID char(2) not null,
	primary key (CONTRACT_ID, SITE_ID)
);
CREATE TABLE b_adv_contract_2_type
(
	CONTRACT_ID int(18) not null default '0',
	TYPE_SID varchar(255) not null,
	primary key (CONTRACT_ID, TYPE_SID)
);
CREATE TABLE b_adv_contract_2_weekday
(
	CONTRACT_ID int(18) not null default '0',
	C_WEEKDAY varchar(10) not null,
	C_HOUR int(2) not null default '0',
	primary key (CONTRACT_ID, C_WEEKDAY, C_HOUR)
);
CREATE TABLE b_adv_type
(
	SID varchar(255) not null,
	ACTIVE char(1) not null default 'Y',
	SORT int(18) not null default '100',
	NAME varchar(255),
	DESCRIPTION text,
	DATE_CREATE datetime,
	CREATED_BY int(18),
	DATE_MODIFY datetime,
	MODIFIED_BY int(18),
	primary key (SID)
);
CREATE TABLE b_b24connector_buttons
(
	ID INT NOT NULL,
	APP_ID INT NOT NULL,
	ADD_DATE DATETIME NOT NULL,
	ADD_BY INT NOT NULL,
	NAME VARCHAR(255) NULL,
	SCRIPT TEXT NULL,
	PRIMARY KEY(ID)
);
CREATE TABLE b_bp_debugger_session (
	ID varchar(32) NOT NULL,
	MODULE_ID varchar(32) NULL,
	ENTITY varchar(64) NOT NULL,
	DOCUMENT_TYPE varchar(128) NOT NULL,
	DOCUMENT_CATEGORY_ID int NULL,
	MODE tinyint unsigned NOT NULL,
	TITLE varchar(256) NULL,
	STARTED_BY int NOT NULL,
	STARTED_DATE datetime NOT NULL,
	FINISHED_DATE datetime,
	ACTIVE char(1) NOT NULL,
	FIXED char(1) NOT NULL,
	DEBUGGER_STATE tinyint NOT NULL default -1,
	primary key (ID)
);
CREATE TABLE b_calendar_type
(
	XML_ID varchar(255) not null,
	NAME  varchar(255) null,
	DESCRIPTION text null,
	EXTERNAL_ID varchar(100) null,
	ACTIVE char(1) not null default 'Y',
	primary key (XML_ID)
);
CREATE TABLE b_catalog_currency
(
	CURRENCY char(3) not null,
	AMOUNT_CNT int not null default 1,
	AMOUNT decimal(18, 4) null,
	SORT int not null default 100,
	DATE_UPDATE datetime not null,
	NUMCODE char(3) null,
	BASE char(1) not null default 'N',
	CREATED_BY int(18) null,
	DATE_CREATE datetime null,
	MODIFIED_BY int(18) null,
	CURRENT_BASE_RATE decimal(26, 12) null,
	primary key (CURRENCY)
);
CREATE TABLE b_catalog_currency_lang
(
	CURRENCY char(3) not null,
	LID char(2) not null,
	FORMAT_STRING varchar(50) not null,
	FULL_NAME varchar(50) null,
	DEC_POINT varchar(16) null default '.',
	THOUSANDS_SEP varchar(16) null default ' ',
	DECIMALS tinyint not null default 2,
	THOUSANDS_VARIANT char(1) null,
	HIDE_ZERO char(1) not null default 'N',
	CREATED_BY int(18) null,
	DATE_CREATE datetime null,
	MODIFIED_BY int(18) null,
	TIMESTAMP_X datetime null,
	primary key (CURRENCY, LID)
);
CREATE TABLE b_catalog_exported_product_queue
(
	QUEUE_ID int not null,
	PRODUCT_IDS text not null,
	primary key (QUEUE_ID)
);
CREATE TABLE b_catalog_load
(
	NAME varchar(250) not null,
	VALUE text not null,
	TYPE char(1) not null default 'I',
	LAST_USED char(1) not null default 'N',
	primary key (NAME, TYPE)
);
CREATE TABLE b_catalog_product
(
	ID int not null,
	QUANTITY double not null,
	QUANTITY_TRACE char(1) not null default 'N',
	WEIGHT double not null default '0',
	TIMESTAMP_X datetime not null,
	PRICE_TYPE char(1) not null default 'S',
	RECUR_SCHEME_LENGTH int null,
	RECUR_SCHEME_TYPE char(1) not null default 'D',
	TRIAL_PRICE_ID int null,
	WITHOUT_ORDER char(1) not null default 'N',
	SELECT_BEST_PRICE char(1) not null default 'Y',
	VAT_ID int(11) null default '0',
	VAT_INCLUDED char(1) null default 'Y',
	CAN_BUY_ZERO char(1) not null default 'N',
	NEGATIVE_AMOUNT_TRACE char(1) not null default 'D',
	TMP_ID varchar(40) null,
	PURCHASING_PRICE decimal(18,2) null,
	PURCHASING_CURRENCY char(3) null,
	BARCODE_MULTI char(1) not null default 'N',
	QUANTITY_RESERVED double null default '0',
	SUBSCRIBE char(1) null,
	WIDTH double null,
	LENGTH double null,
	HEIGHT double null,
	MEASURE int null,
	TYPE int null,
	AVAILABLE char(1) null,
	BUNDLE char(1) null,
	primary key (ID)
);
CREATE TABLE b_conv_context_attribute
(
	CONTEXT_ID int unsigned not null,
	NAME       varchar(30)  not null,
	VALUE      varchar(30)  not null,
	primary key (CONTEXT_ID, NAME)
);
CREATE TABLE b_conv_context_counter_day
(
	DAY        date         not null,
	CONTEXT_ID int unsigned not null,
	NAME       varchar(30)  not null,
	VALUE      float        not null,
	primary key (DAY, CONTEXT_ID, NAME)
);
CREATE TABLE b_conv_context_entity_item
(
	ENTITY     varchar(30)  not null,
	ITEM       varchar(30)  not null,
	CONTEXT_ID int unsigned not null,
	primary key (ENTITY, ITEM)
);
CREATE TABLE b_counter_data
(
  ID varchar(16) NOT NULL,
  TYPE varchar(30) NOT NULL,
  DATA text NOT NULL,
  PRIMARY KEY (ID)
);
CREATE TABLE b_culture (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CODE TEXT,
    NAME TEXT,
    FORMAT_DATE TEXT,
    FORMAT_DATETIME TEXT,
    FORMAT_NAME TEXT,
    WEEK_START INTEGER DEFAULT 1,
    CHARSET TEXT,
    DIRECTION TEXT DEFAULT 'Y',
    SHORT_DATE_FORMAT TEXT DEFAULT 'n/j/Y',
    MEDIUM_DATE_FORMAT TEXT DEFAULT 'M j, Y',
    LONG_DATE_FORMAT TEXT DEFAULT 'F j, Y',
    FULL_DATE_FORMAT TEXT DEFAULT 'l, F j, Y',
    DAY_MONTH_FORMAT TEXT DEFAULT 'F j',
    DAY_SHORT_MONTH_FORMAT TEXT DEFAULT 'M j',
    DAY_OF_WEEK_MONTH_FORMAT TEXT DEFAULT 'l, F j',
    SHORT_DAY_OF_WEEK_MONTH_FORMAT TEXT DEFAULT 'D, F j',
    SHORT_DAY_OF_WEEK_SHORT_MONTH_FORMAT TEXT DEFAULT 'D, M j',
    SHORT_TIME_FORMAT TEXT DEFAULT 'g:i a',
    LONG_TIME_FORMAT TEXT DEFAULT 'g:i:s a',
    AM_VALUE TEXT DEFAULT 'am',
    PM_VALUE TEXT DEFAULT 'pm',
    NUMBER_THOUSANDS_SEPARATOR TEXT DEFAULT ',',
    NUMBER_DECIMAL_SEPARATOR TEXT DEFAULT '.',
    NUMBER_DECIMALS INTEGER DEFAULT 2
);
CREATE TABLE b_event_attachment
(
  EVENT_ID int not null,
  FILE_ID int not null,
  IS_FILE_COPIED char(1) not null default 'Y',
  PRIMARY KEY (EVENT_ID, FILE_ID)
);
CREATE TABLE b_event_log (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TIMESTAMP_X TIMESTAMP NULL,
    SEVERITY TEXT,
    AUDIT_TYPE_ID TEXT,
    MODULE_ID TEXT,
    ITEM_ID TEXT,
    REMOTE_ADDR TEXT,
    USER_AGENT TEXT,
    REQUEST_URI TEXT,
    SITE_ID TEXT,
    USER_ID INTEGER,
    GUEST_ID INTEGER,
    DESCRIPTION TEXT
);
CREATE TABLE b_event_message_attachment
(
  EVENT_MESSAGE_ID int not null,
  FILE_ID int not null,
  PRIMARY KEY (EVENT_MESSAGE_ID, FILE_ID)
);
CREATE TABLE b_event_message_site
(
	EVENT_MESSAGE_ID int not null,
	SITE_ID char(2) not null,
	PRIMARY KEY (EVENT_MESSAGE_ID, SITE_ID)
);
CREATE TABLE b_form_2_mail_template (
	FORM_ID int(18) not null default '0',
	MAIL_TEMPLATE_ID int(18) not null default '0',
	primary key (FORM_ID, MAIL_TEMPLATE_ID)
);
CREATE TABLE b_form_2_site (
	FORM_ID int(18) not null default '0',
	SITE_ID char(2) not null,
	primary key (FORM_ID, SITE_ID)
);
CREATE TABLE b_form_status_2_mail_template (
	STATUS_ID int(18) not null default '0',
	MAIL_TEMPLATE_ID int(18) not null default '0',
	primary key (STATUS_ID, MAIL_TEMPLATE_ID)
);
CREATE TABLE b_forum2site
(
	FORUM_ID int not null,
	SITE_ID char(2) not null,
	PATH2FORUM_MESSAGE varchar(250) null,
	primary key (FORUM_ID, SITE_ID)
);
CREATE TABLE b_forum_points_lang
(
	POINTS_ID int not null,
	LID char(2) not null,
	NAME varchar(250) null,
	primary key (POINTS_ID, LID)
);
CREATE TABLE b_geoname
(
	ID bigint unsigned not null,
	LANGUAGE_CODE varchar(35),
	NAME varchar(600),
	PRIMARY KEY(ID, LANGUAGE_CODE)
);
CREATE TABLE b_group (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TIMESTAMP_X TIMESTAMP NULL,
    ACTIVE TEXT NOT NULL DEFAULT 'Y',
    C_SORT INTEGER DEFAULT 100,
    ANONYMOUS TEXT NOT NULL DEFAULT 'N',
    NAME TEXT,
    DESCRIPTION TEXT
);
CREATE TABLE b_group_collection_task
(
	GROUP_ID int not null,
	TASK_ID int not null,
	COLLECTION_ID int not null,
	primary key (GROUP_ID,TASK_ID,COLLECTION_ID)
);
CREATE TABLE b_group_subordinate(
	ID int not null,
	AR_SUBGROUP_ID text not null,
	PRIMARY KEY (ID)
);
CREATE TABLE b_group_task
(
	GROUP_ID int not null,
	TASK_ID int not null,
	EXTERNAL_ID varchar(50) default '',
	PRIMARY KEY (GROUP_ID,TASK_ID)
);
CREATE TABLE b_iblock (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TIMESTAMP_X TEXT,
    IBLOCK_TYPE_ID TEXT NOT NULL,
    LID TEXT DEFAULT 's1',
    CODE TEXT,
    NAME TEXT NOT NULL,
    ACTIVE TEXT DEFAULT 'Y',
    SORT INTEGER DEFAULT 500,
    LIST_PAGE_URL TEXT,
    DETAIL_PAGE_URL TEXT,
    SECTION_PAGE_URL TEXT,
    VERSION INTEGER DEFAULT 2,
    INDEX_ELEMENT TEXT DEFAULT 'N',
    INDEX_SECTION TEXT DEFAULT 'N',
    WORKFLOW TEXT DEFAULT 'N',
    BIZPROC TEXT DEFAULT 'N'
);
CREATE TABLE b_iblock_cache
(
	CACHE_KEY varchar(35) not null,
	CACHE longtext not null,
	CACHE_DATE datetime not null,
	primary key (CACHE_KEY)
);
CREATE TABLE b_iblock_element (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TIMESTAMP_X TEXT,
    MODIFIED_BY INTEGER,
    DATE_CREATE TEXT,
    CREATED_BY INTEGER,
    IBLOCK_ID INTEGER NOT NULL,
    IBLOCK_SECTION_ID INTEGER,
    ACTIVE TEXT DEFAULT 'Y',
    ACTIVE_FROM TEXT,
    ACTIVE_TO TEXT,
    SORT INTEGER DEFAULT 500,
    NAME TEXT NOT NULL,
    PREVIEW_PICTURE INTEGER,
    PREVIEW_TEXT TEXT,
    PREVIEW_TEXT_TYPE TEXT DEFAULT 'text',
    DETAIL_PICTURE INTEGER,
    DETAIL_TEXT TEXT,
    DETAIL_TEXT_TYPE TEXT DEFAULT 'text',
    CODE TEXT,
    XML_ID TEXT,
    WF_STATUS_ID INTEGER,
    SHOW_COUNTER INTEGER DEFAULT 0
);
CREATE TABLE b_iblock_section (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TIMESTAMP_X TEXT NOT NULL,
    MODIFIED_BY INTEGER,
    DATE_CREATE TEXT,
    CREATED_BY INTEGER,
    IBLOCK_ID INTEGER NOT NULL,
    IBLOCK_SECTION_ID INTEGER,
    ACTIVE TEXT DEFAULT 'Y',
    GLOBAL_ACTIVE TEXT DEFAULT 'Y',
    SORT INTEGER DEFAULT 500,
    NAME TEXT NOT NULL,
    PICTURE INTEGER,
    LEFT_MARGIN INTEGER DEFAULT 1,
    RIGHT_MARGIN INTEGER DEFAULT 2,
    DEPTH_LEVEL INTEGER DEFAULT 1,
    DESCRIPTION TEXT,
    DESCRIPTION_TYPE TEXT DEFAULT 'text',
    CODE TEXT,
    XML_ID TEXT,
    TMP_ID TEXT
);
CREATE TABLE b_iblock_site (
    IBLOCK_ID INTEGER NOT NULL,
    SITE_ID TEXT NOT NULL,
    PRIMARY KEY (IBLOCK_ID, SITE_ID)
);
CREATE TABLE b_iblock_type (
    ID TEXT NOT NULL PRIMARY KEY,
    SECTIONS TEXT DEFAULT 'Y',
    EDIT_FILE_BEFORE TEXT,
    EDIT_FILE_AFTER TEXT,
    IN_RSS TEXT DEFAULT 'N',
    SORT INTEGER DEFAULT 500
);
CREATE TABLE b_iblock_type_lang (
    IBLOCK_TYPE_ID TEXT NOT NULL,
    LID TEXT NOT NULL,
    NAME TEXT,
    SECTIONS_NAME TEXT,
    ELEMENTS_NAME TEXT,
    PRIMARY KEY (IBLOCK_TYPE_ID, LID)
);
CREATE TABLE b_lang (
    LID TEXT NOT NULL PRIMARY KEY,
    SORT INTEGER NOT NULL DEFAULT 100,
    DEF TEXT NOT NULL DEFAULT 'N',
    ACTIVE TEXT NOT NULL DEFAULT 'Y',
    NAME TEXT,
    DIR TEXT,
    FORMAT_DATE TEXT,
    FORMAT_DATETIME TEXT,
    FORMAT_NAME TEXT,
    WEEK_START INTEGER,
    CHARSET TEXT,
    LANGUAGE_ID TEXT,
    DOC_ROOT TEXT,
    DOMAIN_LIMITED TEXT NOT NULL DEFAULT 'N',
    SERVER_NAME TEXT,
    SITE_NAME TEXT,
    EMAIL TEXT,
    CULTURE_ID INTEGER
);
CREATE TABLE b_lang_domain (
    LID TEXT NOT NULL,
    DOMAIN TEXT NOT NULL,
    PRIMARY KEY (LID, DOMAIN)
);
CREATE TABLE b_language (
    LID TEXT NOT NULL PRIMARY KEY,
    SORT INTEGER NOT NULL DEFAULT 100,
    DEF TEXT NOT NULL DEFAULT 'N',
    ACTIVE TEXT NOT NULL DEFAULT 'Y',
    NAME TEXT,
    FORMAT_DATE TEXT,
    FORMAT_DATETIME TEXT,
    FORMAT_NAME TEXT,
    CHARSET TEXT,
    DIRECTION TEXT,
    CULTURE_ID INTEGER,
    CODE TEXT
);
CREATE TABLE b_learn_exceptions_log (
  DATE_REGISTERED datetime NOT NULL,
  CODE int(11) NOT NULL,
  MESSAGE text NOT NULL,
  FFILE text NOT NULL,
  LINE int(11) NOT NULL,
  BACKTRACE text NOT NULL
);
CREATE TABLE b_learn_lesson_edges
(
	SOURCE_NODE INT NOT NULL ,
	TARGET_NODE INT NOT NULL ,
	SORT INT NOT NULL DEFAULT '500',
	PRIMARY KEY ( SOURCE_NODE , TARGET_NODE )
);
CREATE TABLE b_learn_publish_prohibition
(
	COURSE_LESSON_ID INT UNSIGNED NOT NULL ,
	PROHIBITED_LESSON_ID INT UNSIGNED NOT NULL ,
	PRIMARY KEY ( COURSE_LESSON_ID , PROHIBITED_LESSON_ID )
);
CREATE TABLE b_learn_rights
(
	LESSON_ID INT UNSIGNED NOT NULL ,
	SUBJECT_ID VARCHAR( 100 ) NOT NULL ,
	TASK_ID INT NOT NULL ,
	PRIMARY KEY ( LESSON_ID , SUBJECT_ID )
);
CREATE TABLE b_learn_rights_all
(
	SUBJECT_ID VARCHAR( 100 ) NOT NULL ,
	TASK_ID INT NOT NULL ,
	PRIMARY KEY ( SUBJECT_ID )
);
CREATE TABLE b_learn_student
(
	USER_ID int(18) not null,
	TRANSCRIPT int(11) NOT NULL,
	PUBLIC_PROFILE char(1) not null default 'N',
	RESUME text,
	PRIMARY KEY(USER_ID)
);
CREATE TABLE b_location_addr_fld(
	`ADDRESS_ID` INT NOT NULL,
	`TYPE` INT NOT NULL,
	`VALUE` VARCHAR(1024) NULL,
	`VALUE_NORMALIZED` VARCHAR(1024) NULL,
	PRIMARY KEY (`ADDRESS_ID`, `TYPE`)
);
CREATE TABLE b_location_source(
   `CODE` VARCHAR(15) NOT NULL,
   `NAME` VARCHAR(255) NOT NULL,
   `CONFIG` longtext,
   PRIMARY KEY (`CODE`)
);
CREATE TABLE b_location_static_map_file(
	`HASH` CHAR(40) NOT NULL,
	`FILE_ID` INT NOT NULL,
	PRIMARY KEY (`HASH`)
);
CREATE TABLE b_mail_message_upload_queue
(
   ID VARCHAR(32) NOT NULL,
   MAILBOX_ID INT NOT NULL,
   SYNC_STAGE INT NOT NULL DEFAULT 0,
   SYNC_LOCK INT NOT NULL DEFAULT 0,
   ATTEMPTS INT NOT NULL DEFAULT 0,
   PRIMARY KEY (ID, MAILBOX_ID)
);
CREATE TABLE b_mail_spam_weight
(
   WORD_ID varchar(32) not null,
   WORD_REAL varchar(50) not null,
   GOOD_CNT int(18) not null default '0',
   BAD_CNT int(18) not null default '0',
   TOTAL_CNT int(18) not null default '0',
   TIMESTAMP_X timestamp,
   primary key (WORD_ID)
);
CREATE TABLE b_main_mail_sender_send_counter
(
    DATE_STAT DATE NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    CNT INT NOT NULL,
    PRIMARY KEY (DATE_STAT, EMAIL)
);
CREATE TABLE b_medialib_collection_item
(
	COLLECTION_ID int not null,
	ITEM_ID int not null,
	primary key (ITEM_ID,COLLECTION_ID)
);
CREATE TABLE `b_mobileapp_app` (
  `CODE`           VARCHAR(50) NOT NULL,
  `SHORT_NAME`     VARCHAR(50) NOT NULL,
  `NAME`           VARCHAR(50) NOT NULL,
  `DESCRIPTION`    TEXT        NOT NULL,
  `FILES`          TEXT        NOT NULL,
  `LAUNCH_ICONS`   TEXT        NOT NULL,
  `LAUNCH_SCREENS` TEXT        NOT NULL,
  `FOLDER`         VARCHAR(50) NOT NULL,
  `DATE_CREATE`    DATETIME    NOT NULL,
  PRIMARY KEY (`CODE`)
);
CREATE TABLE `b_mobileapp_config` (
  `APP_CODE`    VARCHAR(150) NOT NULL,
  `PLATFORM`    VARCHAR(150) NOT NULL,
  `PARAMS`      TEXT         NOT NULL,
  `DATE_CREATE` DATETIME     NOT NULL,
  PRIMARY KEY (`APP_CODE`, `PLATFORM`)
);
CREATE TABLE b_module (
    ID TEXT NOT NULL PRIMARY KEY,
    DATE_ACTIVE TIMESTAMP NULL
);
CREATE TABLE b_module_to_module (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TIMESTAMP_X TEXT,
    SORT INTEGER NOT NULL DEFAULT 100,
    FROM_MODULE_ID TEXT NOT NULL,
    MESSAGE_ID TEXT NOT NULL,
    TO_MODULE_ID TEXT NOT NULL,
    TO_PATH TEXT,
    TO_CLASS TEXT,
    TO_METHOD TEXT,
    TO_METHOD_ARG TEXT,
    VERSION INTEGER,
    UNIQUE_ID TEXT NOT NULL
);
CREATE TABLE `b_numerator_sequence`
(
	`NUMERATOR_ID` INT NOT NULL DEFAULT '0',
	`KEY` VARCHAR(32) NOT NULL DEFAULT '0',
	`TEXT_KEY` VARCHAR(50) NULL DEFAULT NULL,
	`NEXT_NUMBER` INT NULL DEFAULT NULL,
	`LAST_INVOCATION_TIME` INT NULL DEFAULT NULL,
	PRIMARY KEY (`NUMERATOR_ID`, `KEY`)
);
CREATE TABLE b_option (
    MODULE_ID TEXT NOT NULL,
    NAME TEXT NOT NULL,
    VALUE TEXT,
    DESCRIPTION TEXT,
    SITE_ID TEXT NOT NULL,
    PRIMARY KEY (MODULE_ID, NAME, SITE_ID)
);
CREATE TABLE b_perf_sql_backtrace
(
	SQL_ID INT(18),
	NN INT(18),
	FILE_NAME varchar(500),
	LINE_NO INT(18),
	CLASS_NAME varchar(500),
	FUNCTION_NAME varchar(500),
	CONSTRAINT pk_b_perf_sql_backtrace PRIMARY KEY (SQL_ID, NN)
);
CREATE TABLE b_rating_prepare
(
	ID int not null,
	PRIMARY KEY (ID)
);
CREATE TABLE b_rating_voting_reaction
(
	ENTITY_TYPE_ID varchar(50) not null,
	ENTITY_ID int not null,
	REACTION varchar(8) not null default '',
	TOTAL_VOTES int not null,
	PRIMARY KEY (ENTITY_TYPE_ID, ENTITY_ID, REACTION)
);
CREATE TABLE b_rest_free_app
(
	APP_CODE VARCHAR(128) NOT NULL UNIQUE,
	PRIMARY KEY (APP_CODE)
);
CREATE TABLE b_rest_placement_lang
(
	ID INT AUTO_INCREMENT,
	PLACEMENT_ID INT NOT NULL,
	LANGUAGE_ID VARCHAR(2) NOT NULL,
	TITLE VARCHAR(255) NULL,
	DESCRIPTION VARCHAR(255) NULL,
	GROUP_NAME VARCHAR(255) NULL,
	CONSTRAINT b_rest_placement_lang_pk
	PRIMARY KEY (ID),
	constraint b_rest_placement_lang_unique
	unique (PLACEMENT_ID, LANGUAGE_ID)
);
CREATE TABLE b_rest_stat
(
	STAT_DATE DATE NOT NULL,
	APP_ID INT(11) NOT NULL,
	METHOD_ID INT NOT NULL,
	HOUR_0 INT NOT NULL DEFAULT 0,
	HOUR_1 INT NOT NULL DEFAULT 0,
	HOUR_2 INT NOT NULL DEFAULT 0,
	HOUR_3 INT NOT NULL DEFAULT 0,
	HOUR_4 INT NOT NULL DEFAULT 0,
	HOUR_5 INT NOT NULL DEFAULT 0,
	HOUR_6 INT NOT NULL DEFAULT 0,
	HOUR_7 INT NOT NULL DEFAULT 0,
	HOUR_8 INT NOT NULL DEFAULT 0,
	HOUR_9 INT NOT NULL DEFAULT 0,
	HOUR_10 INT NOT NULL DEFAULT 0,
	HOUR_11 INT NOT NULL DEFAULT 0,
	HOUR_12 INT NOT NULL DEFAULT 0,
	HOUR_13 INT NOT NULL DEFAULT 0,
	HOUR_14 INT NOT NULL DEFAULT 0,
	HOUR_15 INT NOT NULL DEFAULT 0,
	HOUR_16 INT NOT NULL DEFAULT 0,
	HOUR_17 INT NOT NULL DEFAULT 0,
	HOUR_18 INT NOT NULL DEFAULT 0,
	HOUR_19 INT NOT NULL DEFAULT 0,
	HOUR_20 INT NOT NULL DEFAULT 0,
	HOUR_21 INT NOT NULL DEFAULT 0,
	HOUR_22 INT NOT NULL DEFAULT 0,
	HOUR_23 INT NOT NULL DEFAULT 0,
	PRIMARY KEY (APP_ID, STAT_DATE, METHOD_ID)
);
CREATE TABLE b_sale_basket_archive_packed(
	BASKET_ARCHIVE_ID int NOT NULL,
	BASKET_DATA mediumtext NULL,
	PRIMARY KEY (BASKET_ARCHIVE_ID)
);
CREATE TABLE b_sale_bizval
(
	CODE_KEY varchar(50) not null,
	CONSUMER_KEY varchar(50) not null,
	PERSON_TYPE_ID int not null,
	PROVIDER_KEY varchar(50) not null,
	PROVIDER_VALUE text null,
	primary key(CODE_KEY, CONSUMER_KEY, PERSON_TYPE_ID)
);
CREATE TABLE b_sale_bizval_code_1c
(
	PERSON_TYPE_ID int not null,
	CODE_INDEX int not null,
	NAME varchar(255) not null,
	primary key(PERSON_TYPE_ID, CODE_INDEX)
);
CREATE TABLE b_sale_bizval_persondomain
(
	PERSON_TYPE_ID int not null,
	DOMAIN char(1) not null,
	primary key(PERSON_TYPE_ID, DOMAIN)
);
CREATE TABLE b_sale_cashbox_connect (
	HASH VARCHAR(100) NOT NULL,
	ACTIVE char(1) not null default 'Y',
	DATE_CREATE datetime NOT NULL,
	PRIMARY KEY (HASH)
);
CREATE TABLE b_sale_company2location
(
	COMPANY_ID int not null,
	LOCATION_CODE varchar(100) not null,
	LOCATION_TYPE char(1) not null default 'L',
	primary key (COMPANY_ID, LOCATION_CODE, LOCATION_TYPE)
);
CREATE TABLE b_sale_company2service
(
	COMPANY_ID int not null,
	SERVICE_ID int not null,
	SERVICE_TYPE int not null,
	primary key (COMPANY_ID, SERVICE_ID, SERVICE_TYPE)
);
CREATE TABLE b_sale_delivery2location
(
	DELIVERY_ID int not null,
	LOCATION_CODE varchar(100) not null,
	LOCATION_TYPE char(2) not null default 'L',
	primary key (DELIVERY_ID, LOCATION_CODE, LOCATION_TYPE)
);
CREATE TABLE b_sale_lang
(
	LID char(2) not null,
	CURRENCY char(3) not null,
	primary key (LID)
);
CREATE TABLE b_sale_loc_2site
(
	LOCATION_ID int not null,
	SITE_ID char(2) not null,
	LOCATION_TYPE char(1) not null default 'L',
	primary key (SITE_ID, LOCATION_ID, LOCATION_TYPE)
);
CREATE TABLE b_sale_loc_def2site(
	LOCATION_CODE varchar(100) not null,
	SITE_ID char(2) not null,
	SORT int default '100',
	primary key (LOCATION_CODE, SITE_ID)
);
CREATE TABLE b_sale_location2location_group
(
	LOCATION_ID int not null,
	LOCATION_GROUP_ID int not null,
	primary key (LOCATION_ID, LOCATION_GROUP_ID)
);
CREATE TABLE b_sale_order_archive_packed(
	ORDER_ARCHIVE_ID int NOT NULL,
	ORDER_DATA mediumtext NULL,
	PRIMARY KEY (ORDER_ARCHIVE_ID)
);
CREATE TABLE b_sale_order_props_relation
(
	PROPERTY_ID INT NOT NULL,
	ENTITY_ID VARCHAR(35) NOT NULL,
	ENTITY_TYPE CHAR(1) NOT NULL,
	PRIMARY KEY (PROPERTY_ID, ENTITY_ID, ENTITY_TYPE)
);
CREATE TABLE b_sale_person_type_site (
	PERSON_TYPE_ID int(18) NOT NULL default '0',
	SITE_ID char(2) NOT NULL default '',
	PRIMARY KEY  (PERSON_TYPE_ID, SITE_ID)
);
CREATE TABLE b_sale_status
(
	ID varchar(2) not null,
	TYPE char(1) not null default 'O',
	SORT int not null default '100',
	NOTIFY char(1) not null default 'Y',
	COLOR varchar(10) null,
	XML_ID varchar(255) null,
	primary key (ID)
);
CREATE TABLE b_sale_status_group_task
(
	STATUS_ID varchar(2) not null,
	GROUP_ID  int(18) not null,
	TASK_ID   int(18) not null,
	primary key (STATUS_ID, GROUP_ID, TASK_ID)
);
CREATE TABLE b_sale_status_lang
(
	STATUS_ID varchar(2) not null,
	LID char(2) not null,
	NAME varchar(100) not null,
	DESCRIPTION varchar(250) null,
	primary key (STATUS_ID, LID)
);
CREATE TABLE b_sale_tax2location
(
	TAX_RATE_ID int not null,
	LOCATION_CODE varchar(100) not null,
	LOCATION_TYPE char(1) not null default 'L',
	primary key (TAX_RATE_ID, LOCATION_CODE, LOCATION_TYPE)
);
CREATE TABLE b_sale_tax_exempt2group
(
	GROUP_ID int not null,
	TAX_ID int not null,
	primary key (GROUP_ID, TAX_ID)
);
CREATE TABLE b_sale_yandex_settings
(
	SHOP_ID INT NOT NULL,
	CSR TEXT NULL,
	SIGN TEXT NULL,
	CERT TEXT NULL,
	PKEY TEXT NULL,
	PUB_KEY TEXT NULL,
	primary key (SHOP_ID)
);
CREATE TABLE b_sec_iprule_excl_ip
(
	IPRULE_ID INT(11) NOT NULL REFERENCES b_sec_iprule(ID),
	RULE_IP VARCHAR(50) NOT NULL,
	SORT INT(11) NOT NULL DEFAULT 500,
	IP_START bigint(18),
	IP_END bigint(18),
	PRIMARY KEY(IPRULE_ID, RULE_IP)
);
CREATE TABLE b_sec_iprule_excl_mask
(
	IPRULE_ID INT(11) NOT NULL REFERENCES b_sec_iprule(ID),
	RULE_MASK VARCHAR(250),
	SORT INT(11) NOT NULL DEFAULT 500,
	LIKE_MASK VARCHAR(250),
	PREG_MASK VARCHAR(250),
	PRIMARY KEY(IPRULE_ID, RULE_MASK)
);
CREATE TABLE b_sec_iprule_incl_ip
(
	IPRULE_ID INT(11) NOT NULL REFERENCES b_sec_iprule(ID),
	RULE_IP VARCHAR(50) NOT NULL,
	SORT INT(11) NOT NULL DEFAULT 500,
	IP_START bigint(18),
	IP_END bigint(18),
	PRIMARY KEY(IPRULE_ID, RULE_IP)
);
CREATE TABLE b_sec_iprule_incl_mask
(
	IPRULE_ID INT(11) NOT NULL REFERENCES b_sec_iprule(ID),
	RULE_MASK VARCHAR(250),
	SORT INT(11) NOT NULL DEFAULT 500,
	LIKE_MASK VARCHAR(250),
	PREG_MASK VARCHAR(250),
	PRIMARY KEY(IPRULE_ID, RULE_MASK)
);
CREATE TABLE b_sec_redirect_url
(
	IS_SYSTEM CHAR(1) NOT NULL DEFAULT 'Y',
	SORT INT(11) NOT NULL DEFAULT 500,
	URL VARCHAR(250) NOT NULL,
	PARAMETER_NAME VARCHAR(250) NOT NULL
);
CREATE TABLE b_sec_session
(
	SESSION_ID VARCHAR(250) NOT NULL,
	TIMESTAMP_X TIMESTAMP NOT NULL,
	SESSION_DATA LONGTEXT,
	PRIMARY KEY(SESSION_ID)
);
CREATE TABLE b_sec_user
(
	USER_ID INT(11) NOT NULL REFERENCES b_user(ID),
	ACTIVE CHAR(1) NOT NULL DEFAULT 'N',
	SECRET VARCHAR(64),
	TYPE VARCHAR(16) NOT NULL,
	INIT_PARAMS text,
	PARAMS text,
	ATTEMPTS int(18),
	INITIAL_DATE datetime,
	SKIP_MANDATORY CHAR(1) NOT NULL DEFAULT 'N',
	DEACTIVATE_UNTIL datetime,
	PRIMARY KEY (USER_ID)
);
CREATE TABLE b_sec_vendor_notification
(
	`VENDOR_ID` VARCHAR(50) not null,
	`DATA` TEXT,
	PRIMARY KEY(`VENDOR_ID`)
);
CREATE TABLE b_sec_virus
(
	ID VARCHAR(32) NOT NULL,
	TIMESTAMP_X DATETIME NOT NULL,
	SITE_ID CHAR(2),
	SENT CHAR(1) NOT NULL DEFAULT 'N',
	INFO LONGTEXT NOT NULL,
	PRIMARY KEY(ID)
);
CREATE TABLE b_sec_white_list
(
	ID INT(11) NOT NULL,
	WHITE_SUBSTR VARCHAR(250) NOT NULL,
	PRIMARY KEY(ID)
);
CREATE TABLE b_sender_call_log
(
  CALL_ID VARCHAR(255) NOT NULL,
  RECIPIENT_ID INT(11) NOT NULL,
  DATE_INSERT DATETIME NOT NULL,
  PRIMARY KEY (CALL_ID, RECIPIENT_ID)
);
CREATE TABLE b_sender_counter_daily
(
  DATE_STAT DATE NOT NULL,
  SENT_CNT INT NOT NULL DEFAULT 0,
  TEST_SENT_CNT INT NOT NULL DEFAULT 0,
  ERROR_CNT INT NOT NULL DEFAULT 0,
  ABUSE_CNT INT NOT NULL DEFAULT 0,
  PRIMARY KEY (DATE_STAT)
);
CREATE TABLE b_sender_file
(
	`ID`  INT UNSIGNED  auto_increment primary key,
	`FILE_ID`  INT UNSIGNED NOT NULL,
	`ENTITY_TYPE`  INT UNSIGNED NOT NULL,
	`ENTITY_ID`     INT UNSIGNED NOT NULL,
	`DATE_INSERT` datetime NOT NULL
);
CREATE TABLE b_sender_group_connector
(
  GROUP_ID int(11) NOT NULL,
  NAME		VARCHAR(100)	NULL,
  ENDPOINT	LONGTEXT	NULL,
  ADDRESS_COUNT	INT(11)		DEFAULT 0 NOT NULL,
  FILTER_ID varchar(256)
);
CREATE TABLE b_sender_group_thread
(
  `THREAD_ID`   INT UNSIGNED NOT NULL,
  `GROUP_STATE_ID`  INT UNSIGNED NOT NULL,
  `STATUS`      VARCHAR(1)   NOT NULL DEFAULT 'N',
  `STEP`      INT UNSIGNED NOT NULL DEFAULT 0,
  `THREAD_TYPE` TEXT         NOT NULL,
  `EXPIRE_AT`   DATETIME     NOT NULL,
CONSTRAINT `IX_SENDER_GROUP_THREAD_INFO_THREAD_ID_GROUP_STATE` UNIQUE
(`THREAD_ID`, `GROUP_STATE_ID`)
);
CREATE TABLE b_sender_mailing_attachment
(
  CHAIN_ID int(18) not null,
  FILE_ID int(18) not null,
  PRIMARY KEY (CHAIN_ID, FILE_ID)
);
CREATE TABLE b_sender_mailing_subscription
(
  MAILING_ID int(11) not null,
  CONTACT_ID INT(11) not NULL,
  DATE_INSERT	DATETIME NULL,
  IS_UNSUB CHAR(1) DEFAULT 'N'  NOT NULL,
  PRIMARY KEY (MAILING_ID, CONTACT_ID, IS_UNSUB)
);
CREATE TABLE b_sender_mailing_trigger
(
  MAILING_CHAIN_ID int(11) not null,
  IS_TYPE_START int(1) default 1 not null,
  NAME VARCHAR(255) NULL,
  EVENT VARCHAR(255) NOT NULL,
  ENDPOINT TEXT NOT NULL
);
CREATE TABLE b_sender_message_field
(
  MESSAGE_ID INT(11) NOT NULL,
  CODE VARCHAR(255) NOT NULL,
  TYPE VARCHAR(20) NOT NULL,
  VALUE LONGTEXT NULL,
  PRIMARY KEY (MESSAGE_ID, CODE)
);
CREATE TABLE `b_sender_message_utm`
	(
		`MESSAGE_ID`  INT UNSIGNED NOT NULL,
		`CODE`      VARCHAR(70)   NOT NULL,
		`VALUE`     VARCHAR(512)  NOT NULL,
		CONSTRAINT `IX_SENDER_MESSAGE_UTM_MESSAGE_ID_CODE` UNIQUE
			(`MESSAGE_ID`, `CODE`)
	);
CREATE TABLE `b_sender_posting_thread`
(
	`THREAD_ID`   INT UNSIGNED NOT NULL,
	`POSTING_ID`  INT UNSIGNED NOT NULL,
	`STATUS`      VARCHAR(1)   NOT NULL DEFAULT 'N',
	`THREAD_TYPE` TEXT         NOT NULL,
	`EXPIRE_AT`   DATETIME     NOT NULL,
	CONSTRAINT `IX_SENDER_THREAD_INFO_POSTING_ID_THREAD_ID` UNIQUE (`THREAD_ID`, `POSTING_ID`)
);
CREATE TABLE b_sender_queue
(
  ENTITY_TYPE varchar(20) NOT NULL,
  ENTITY_ID varchar(10) NOT NULL,
  LAST_ITEM varchar(255) NOT NULL,
  PRIMARY KEY (ENTITY_TYPE, ENTITY_ID)
);
CREATE TABLE b_sender_timeline_queue
(
	ID              int unsigned auto_increment
		primary key,
	POSTING_ID      int unsigned           not null,
	RECIPIENT_ID    int unsigned           null,
	FIELDS          longtext               null,
	ENTITY_ID       int unsigned           null,
	CONTACT_TYPE_ID int unsigned           null,
	CONTACT_CODE    varchar(255)           not null,
	STATUS          varchar(1) default 'N' not null,
	DATE_INSERT     datetime               not null
);
CREATE TABLE b_seo_adv_link
(
	LINK_TYPE char(1) NOT NULL,
	LINK_ID int(18) NOT NULL,
	BANNER_ID int(11) NOT NULL,
	PRIMARY KEY (LINK_TYPE,LINK_ID,BANNER_ID)
);
CREATE TABLE b_site (
    LID TEXT NOT NULL PRIMARY KEY,
    SORT INTEGER NOT NULL DEFAULT 100,
    DEF TEXT NOT NULL DEFAULT 'N',
    ACTIVE TEXT NOT NULL DEFAULT 'Y',
    NAME TEXT,
    DIR TEXT,
    LANGUAGE_ID TEXT,
    DOC_ROOT TEXT,
    SERVER_NAME TEXT,
    EMAIL TEXT,
    CHARSET TEXT
);
CREATE TABLE b_site_lang (
    LID TEXT NOT NULL,
    SITE_ID TEXT NOT NULL,
    SORT INTEGER NOT NULL DEFAULT 100,
    PRIMARY KEY (LID, SITE_ID)
);
CREATE TABLE b_sms_template_site
(
	TEMPLATE_ID int not null,
	SITE_ID char(2) not null,
	PRIMARY KEY (TEMPLATE_ID, SITE_ID)
);
CREATE TABLE b_stat_country (
   ID char(2) not null,
   SHORT_NAME char(3),
   NAME varchar(50),
   SESSIONS int(18) not null default '0',
   NEW_GUESTS int(18) not null default '0',
   HITS int(18) not null default '0',
   C_EVENTS int(18) not null default '0',
   primary key (ID));
CREATE TABLE b_sticker_group_task
(
	GROUP_ID int not null,
	TASK_ID int not null,
	primary key (GROUP_ID,TASK_ID)
);
CREATE TABLE b_task_operation
(
	TASK_ID int not null,
	OPERATION_ID int not null,
	PRIMARY KEY (TASK_ID,OPERATION_ID)
);
CREATE TABLE b_ticket_dictionary_2_site (
   DICTIONARY_ID int(18) not null default '0',
   SITE_ID char(2) not null,
   primary key (DICTIONARY_ID, SITE_ID));
CREATE TABLE b_ticket_sla_2_category (
   SLA_ID int(18) not null default '0',
   CATEGORY_ID int(18) not null default '0',
   primary key (SLA_ID, CATEGORY_ID));
CREATE TABLE b_ticket_sla_2_criticality (
   SLA_ID int(18) not null default '0',
   CRITICALITY_ID int(18) not null default '0',
   primary key (SLA_ID, CRITICALITY_ID));
CREATE TABLE b_ticket_sla_2_holidays
(
SLA_ID INT(18) not null,
HOLIDAYS_ID INT(18) not null
);
CREATE TABLE b_ticket_sla_2_mark (
   SLA_ID int(18) not null default '0',
   MARK_ID int(18) not null default '0',
   primary key (SLA_ID, MARK_ID));
CREATE TABLE b_ticket_sla_2_site (
  SLA_ID int(18) not null,  
  SITE_ID varchar(5) not null,  
  primary key (SLA_ID, SITE_ID));
CREATE TABLE b_ticket_sla_2_user_group (
   SLA_ID int(18) not null default '0',
   GROUP_ID int(18) not null default '0',
   primary key (SLA_ID, GROUP_ID));
CREATE TABLE b_ticket_user_ugroup (
  USER_ID int(11) NOT NULL default '0',
  GROUP_ID int(11) NOT NULL default '0',
  CAN_VIEW_GROUP_MESSAGES char(1) NOT NULL default 'N',
  CAN_MAIL_GROUP_MESSAGES char(1) NOT NULL default 'N',
  CAN_MAIL_UPDATE_GROUP_MESSAGES char(1) NOT NULL default 'N',
  PRIMARY KEY  (GROUP_ID,USER_ID));
CREATE TABLE b_undo
(
	ID varchar(255) not null,
	MODULE_ID varchar(50),
	UNDO_TYPE varchar(50),
	UNDO_HANDLER varchar(255),
	CONTENT mediumtext,
	USER_ID int,
	TIMESTAMP_X int,
	PRIMARY KEY (ID)
);
CREATE TABLE b_user (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TIMESTAMP_X TIMESTAMP NULL,
    LOGIN TEXT,
    PASSWORD TEXT,
    CHECKWORD TEXT,
    ACTIVE TEXT NOT NULL DEFAULT 'Y',
    NAME TEXT,
    LAST_NAME TEXT,
    EMAIL TEXT,
    DATE_REGISTER TIMESTAMP NULL,
    LID TEXT
);
CREATE TABLE b_user_auth_code
(
	USER_ID int not null,
	CODE_TYPE varchar(20) not null default 'email',
	OTP_SECRET text,
	ATTEMPTS int default 0,
	DATE_SENT datetime,
	DATE_RESENT datetime,
	PRIMARY KEY (USER_ID, CODE_TYPE)
);
CREATE TABLE b_user_digest
(
	USER_ID int not null,
	DIGEST_HA1 varchar(32) not null,
	PRIMARY KEY (USER_ID)
);
CREATE TABLE b_user_field_lang
(
	USER_FIELD_ID int,
	LANGUAGE_ID char(2),
	EDIT_FORM_LABEL varchar(255),
	LIST_COLUMN_LABEL varchar(255),
	LIST_FILTER_LABEL varchar(255),
	ERROR_MESSAGE varchar(255),
	HELP_MESSAGE varchar(255),
	PRIMARY KEY (USER_FIELD_ID, LANGUAGE_ID)
);
CREATE TABLE b_vote_channel_2_site (
	CHANNEL_ID int(18) not null default '0',
	SITE_ID char(2) not null,
	primary key (CHANNEL_ID, SITE_ID));
CREATE INDEX IX_SENDER_FILE_ENTITY_TYPE_ENTITY_ID
    on b_sender_file (`ENTITY_TYPE`, `ENTITY_ID`);
CREATE INDEX IX_SENDER_FILE_FILE_ID
    on b_sender_file (`FILE_ID`);
CREATE INDEX IX_SENDER_GROUP_CONNECTOR on b_sender_group_connector(GROUP_ID);
CREATE INDEX `IX_SENDER_MESSAGE_UTM_CODE` on `b_sender_message_utm` (`CODE`);
CREATE INDEX TARGET_NODE ON b_learn_lesson_edges(TARGET_NODE);
CREATE INDEX ix_b_adv_banner_2_country_2 on b_adv_banner_2_country (CITY_ID, BANNER_ID);
CREATE INDEX ix_b_adv_banner_2_country_3 on b_adv_banner_2_country (BANNER_ID);
CREATE INDEX ix_b_sec_session_time on b_sec_session(TIMESTAMP_X);
CREATE INDEX mail_spam_bad ON b_mail_spam_weight(BAD_CNT);
CREATE INDEX mail_spam_good ON b_mail_spam_weight(GOOD_CNT);
INSERT INTO "b_catalog_currency_lang" ("CURRENCY", "LID", "FORMAT_STRING", "FULL_NAME", "DEC_POINT", "THOUSANDS_SEP", "DECIMALS", "THOUSANDS_VARIANT", "HIDE_ZERO", "CREATED_BY", "DATE_CREATE", "MODIFIED_BY", "TIMESTAMP_X") VALUES ('USD', 'ru', '$#', '������ ���', '.', ',', 2, NULL, 'N', NULL, NULL, NULL, NULL);
INSERT INTO "b_catalog_currency_lang" ("CURRENCY", "LID", "FORMAT_STRING", "FULL_NAME", "DEC_POINT", "THOUSANDS_SEP", "DECIMALS", "THOUSANDS_VARIANT", "HIDE_ZERO", "CREATED_BY", "DATE_CREATE", "MODIFIED_BY", "TIMESTAMP_X") VALUES ('USD', 'en', '$#', 'USA dollar', '.', ',', 2, NULL, 'N', NULL, NULL, NULL, NULL);
INSERT INTO "b_catalog_currency_lang" ("CURRENCY", "LID", "FORMAT_STRING", "FULL_NAME", "DEC_POINT", "THOUSANDS_SEP", "DECIMALS", "THOUSANDS_VARIANT", "HIDE_ZERO", "CREATED_BY", "DATE_CREATE", "MODIFIED_BY", "TIMESTAMP_X") VALUES ('RUR', 'ru', '# ���', '�����', '.', '\\xA0', 2, NULL, 'N', NULL, NULL, NULL, NULL);
INSERT INTO "b_catalog_currency_lang" ("CURRENCY", "LID", "FORMAT_STRING", "FULL_NAME", "DEC_POINT", "THOUSANDS_SEP", "DECIMALS", "THOUSANDS_VARIANT", "HIDE_ZERO", "CREATED_BY", "DATE_CREATE", "MODIFIED_BY", "TIMESTAMP_X") VALUES ('RUR', 'en', '# rub', 'Rouble', '.', '\\xA0', 2, NULL, 'N', NULL, NULL, NULL, NULL);
INSERT INTO "b_culture" ("ID", "CODE", "NAME", "FORMAT_DATE", "FORMAT_DATETIME", "FORMAT_NAME", "WEEK_START", "CHARSET", "DIRECTION", "SHORT_DATE_FORMAT", "MEDIUM_DATE_FORMAT", "LONG_DATE_FORMAT", "FULL_DATE_FORMAT", "DAY_MONTH_FORMAT", "DAY_SHORT_MONTH_FORMAT", "DAY_OF_WEEK_MONTH_FORMAT", "SHORT_DAY_OF_WEEK_MONTH_FORMAT", "SHORT_DAY_OF_WEEK_SHORT_MONTH_FORMAT", "SHORT_TIME_FORMAT", "LONG_TIME_FORMAT", "AM_VALUE", "PM_VALUE", "NUMBER_THOUSANDS_SEPARATOR", "NUMBER_DECIMAL_SEPARATOR", "NUMBER_DECIMALS") VALUES (1, 'ru', 'Russian', 'DD.MM.YYYY', 'DD.MM.YYYY HH:MI:SS', '#NAME# #LAST_NAME#', 1, 'UTF-8', 'Y', 'n/j/Y', 'M j, Y', 'F j, Y', 'l, F j, Y', 'F j', 'M j', 'l, F j', 'D, F j', 'D, M j', 'g:i a', 'g:i:s a', 'am', 'pm', ',', '.', 2);
INSERT INTO "b_group" ("ID", "TIMESTAMP_X", "ACTIVE", "C_SORT", "ANONYMOUS", "NAME", "DESCRIPTION") VALUES (1, NULL, 'Y', 1, 'Y', 'All users', NULL);
INSERT INTO "b_group" ("ID", "TIMESTAMP_X", "ACTIVE", "C_SORT", "ANONYMOUS", "NAME", "DESCRIPTION") VALUES (2, NULL, 'Y', 2, 'N', 'Administrators', NULL);
INSERT INTO "b_iblock" ("ID", "TIMESTAMP_X", "IBLOCK_TYPE_ID", "LID", "CODE", "NAME", "ACTIVE", "SORT", "LIST_PAGE_URL", "DETAIL_PAGE_URL", "SECTION_PAGE_URL", "VERSION", "INDEX_ELEMENT", "INDEX_SECTION", "WORKFLOW", "BIZPROC") VALUES (1, '2026-05-20 14:16:52', 'content', 's1', 'test_iblock', 'Тестовый инфоблок', 'Y', 100, NULL, NULL, NULL, 2, 'N', 'N', 'N', 'N');
INSERT INTO "b_iblock_element" ("ID", "TIMESTAMP_X", "MODIFIED_BY", "DATE_CREATE", "CREATED_BY", "IBLOCK_ID", "IBLOCK_SECTION_ID", "ACTIVE", "ACTIVE_FROM", "ACTIVE_TO", "SORT", "NAME", "PREVIEW_PICTURE", "PREVIEW_TEXT", "PREVIEW_TEXT_TYPE", "DETAIL_PICTURE", "DETAIL_TEXT", "DETAIL_TEXT_TYPE", "CODE", "XML_ID", "WF_STATUS_ID", "SHOW_COUNTER") VALUES (1, '2026-05-20 14:16:52', NULL, '2026-05-20 14:16:52', NULL, 1, 1, 'Y', NULL, NULL, 100, 'Тестовый элемент', NULL, NULL, 'text', NULL, NULL, 'text', 'test-element', 'el-1', NULL, 0);
INSERT INTO "b_iblock_element" ("ID", "TIMESTAMP_X", "MODIFIED_BY", "DATE_CREATE", "CREATED_BY", "IBLOCK_ID", "IBLOCK_SECTION_ID", "ACTIVE", "ACTIVE_FROM", "ACTIVE_TO", "SORT", "NAME", "PREVIEW_PICTURE", "PREVIEW_TEXT", "PREVIEW_TEXT_TYPE", "DETAIL_PICTURE", "DETAIL_TEXT", "DETAIL_TEXT_TYPE", "CODE", "XML_ID", "WF_STATUS_ID", "SHOW_COUNTER") VALUES (2, '2026-05-20 14:16:52', NULL, '2026-05-20 14:16:52', NULL, 1, 2, 'Y', NULL, NULL, 200, 'Элемент в подразделе', NULL, NULL, 'text', NULL, NULL, 'text', 'nested-element', 'el-2', NULL, 0);
INSERT INTO "b_iblock_section" ("ID", "TIMESTAMP_X", "MODIFIED_BY", "DATE_CREATE", "CREATED_BY", "IBLOCK_ID", "IBLOCK_SECTION_ID", "ACTIVE", "GLOBAL_ACTIVE", "SORT", "NAME", "PICTURE", "LEFT_MARGIN", "RIGHT_MARGIN", "DEPTH_LEVEL", "DESCRIPTION", "DESCRIPTION_TYPE", "CODE", "XML_ID", "TMP_ID") VALUES (1, '2026-05-20 14:16:52', NULL, NULL, NULL, 1, NULL, 'Y', 'Y', 100, 'Корневой раздел', NULL, 1, 4, 1, NULL, 'text', 'root', 'sec-root', NULL);
INSERT INTO "b_iblock_section" ("ID", "TIMESTAMP_X", "MODIFIED_BY", "DATE_CREATE", "CREATED_BY", "IBLOCK_ID", "IBLOCK_SECTION_ID", "ACTIVE", "GLOBAL_ACTIVE", "SORT", "NAME", "PICTURE", "LEFT_MARGIN", "RIGHT_MARGIN", "DEPTH_LEVEL", "DESCRIPTION", "DESCRIPTION_TYPE", "CODE", "XML_ID", "TMP_ID") VALUES (2, '2026-05-20 14:16:52', NULL, NULL, NULL, 1, 1, 'Y', 'Y', 200, 'Дочерний раздел', NULL, 2, 3, 2, NULL, 'text', 'child', 'sec-child', NULL);
INSERT INTO "b_iblock_site" ("IBLOCK_ID", "SITE_ID") VALUES (1, 's1');
INSERT INTO "b_iblock_type" ("ID", "SECTIONS", "EDIT_FILE_BEFORE", "EDIT_FILE_AFTER", "IN_RSS", "SORT") VALUES ('content', 'Y', NULL, NULL, 'N', 100);
INSERT INTO "b_iblock_type_lang" ("IBLOCK_TYPE_ID", "LID", "NAME", "SECTIONS_NAME", "ELEMENTS_NAME") VALUES ('content', 'ru', 'Контент', 'Разделы', 'Элементы');
INSERT INTO "b_lang" ("LID", "SORT", "DEF", "ACTIVE", "NAME", "DIR", "FORMAT_DATE", "FORMAT_DATETIME", "FORMAT_NAME", "WEEK_START", "CHARSET", "LANGUAGE_ID", "DOC_ROOT", "DOMAIN_LIMITED", "SERVER_NAME", "SITE_NAME", "EMAIL", "CULTURE_ID") VALUES ('s1', 1, 'Y', 'Y', 'Test', '/', 'DD.MM.YYYY', 'DD.MM.YYYY HH:MI:SS', '#NAME# #LAST_NAME#', NULL, 'UTF-8', 'ru', NULL, 'N', 'localhost', 'Test', 'test@localhost', 1);
INSERT INTO "b_language" ("LID", "SORT", "DEF", "ACTIVE", "NAME", "FORMAT_DATE", "FORMAT_DATETIME", "FORMAT_NAME", "CHARSET", "DIRECTION", "CULTURE_ID", "CODE") VALUES ('ru', 1, 'Y', 'Y', 'Russian', 'DD.MM.YYYY', 'DD.MM.YYYY HH:MI:SS', NULL, 'UTF-8', 'Y', 1, 'ru');
INSERT INTO "b_module" ("ID", "DATE_ACTIVE") VALUES ('main', '2026-05-20 14:17:07');
INSERT INTO "b_module" ("ID", "DATE_ACTIVE") VALUES ('iblock', '2026-05-20 14:17:07');
INSERT INTO "b_option" ("MODULE_ID", "NAME", "VALUE", "DESCRIPTION", "SITE_ID") VALUES ('main', '~crypto_b_salt', 'test_salt', NULL, '');
INSERT INTO "b_option" ("MODULE_ID", "NAME", "VALUE", "DESCRIPTION", "SITE_ID") VALUES ('iblock', 'version', '1', NULL, '');
INSERT INTO "b_site" ("LID", "SORT", "DEF", "ACTIVE", "NAME", "DIR", "LANGUAGE_ID", "DOC_ROOT", "SERVER_NAME", "EMAIL", "CHARSET") VALUES ('s1', 1, 'Y', 'Y', 'Test', '/', 'ru', '', 'localhost', NULL, 'UTF-8');
INSERT INTO "b_site_lang" ("LID", "SITE_ID", "SORT") VALUES ('ru', 's1', 100);
INSERT INTO "b_user" ("ID", "TIMESTAMP_X", "LOGIN", "PASSWORD", "CHECKWORD", "ACTIVE", "NAME", "LAST_NAME", "EMAIL", "DATE_REGISTER", "LID") VALUES (1, NULL, 'admin', '', NULL, 'Y', NULL, NULL, NULL, '2026-05-20 14:16:52', 's1');
COMMIT;
