-- Minimal Bitrix tables for test prolog bootstrap (SQLite).

CREATE TABLE IF NOT EXISTS b_option (
    MODULE_ID TEXT NOT NULL,
    NAME TEXT NOT NULL,
    VALUE TEXT,
    DESCRIPTION TEXT,
    SITE_ID TEXT NOT NULL,
    PRIMARY KEY (MODULE_ID, NAME, SITE_ID)
);

CREATE TABLE IF NOT EXISTS b_module (
    ID TEXT NOT NULL PRIMARY KEY,
    DATE_ACTIVE TIMESTAMP NULL
);

INSERT OR IGNORE INTO b_module (ID) VALUES ('main');

CREATE TABLE IF NOT EXISTS b_module_to_module (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TIMESTAMP_X TEXT,
    SORT INTEGER NOT NULL DEFAULT 100,
    FROM_MODULE_ID TEXT NOT NULL,
    MESSAGE_ID TEXT NOT NULL,
    TO_MODULE_ID TEXT NOT NULL,
    TO_PATH TEXT,
    TO_CLASS TEXT,
    TO_METHOD TEXT,
    TO_METHOD_ARG TEXT,
    VERSION INTEGER,
    UNIQUE_ID TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS b_lang (
    LID TEXT NOT NULL PRIMARY KEY,
    SORT INTEGER NOT NULL DEFAULT 100,
    DEF TEXT NOT NULL DEFAULT 'N',
    ACTIVE TEXT NOT NULL DEFAULT 'Y',
    NAME TEXT,
    DIR TEXT,
    FORMAT_DATE TEXT,
    FORMAT_DATETIME TEXT,
    FORMAT_NAME TEXT,
    WEEK_START INTEGER,
    CHARSET TEXT,
    LANGUAGE_ID TEXT,
    DOC_ROOT TEXT,
    DOMAIN_LIMITED TEXT NOT NULL DEFAULT 'N',
    SERVER_NAME TEXT,
    SITE_NAME TEXT,
    EMAIL TEXT,
    CULTURE_ID INTEGER
);

INSERT OR IGNORE INTO b_lang (
    LID, SORT, DEF, ACTIVE, NAME, DIR, FORMAT_DATE, FORMAT_DATETIME, FORMAT_NAME,
    LANGUAGE_ID, CHARSET, DOMAIN_LIMITED, SERVER_NAME, SITE_NAME, EMAIL, CULTURE_ID
) VALUES (
    's1', 1, 'Y', 'Y', 'Test', '/', 'DD.MM.YYYY', 'DD.MM.YYYY HH:MI:SS', '#NAME# #LAST_NAME#',
    'ru', 'UTF-8', 'N', 'localhost', 'Test', 'test@localhost', 1
);

CREATE TABLE IF NOT EXISTS b_lang_domain (
    LID TEXT NOT NULL,
    DOMAIN TEXT NOT NULL,
    PRIMARY KEY (LID, DOMAIN)
);

CREATE TABLE IF NOT EXISTS b_culture (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CODE TEXT,
    NAME TEXT,
    FORMAT_DATE TEXT,
    FORMAT_DATETIME TEXT,
    FORMAT_NAME TEXT,
    WEEK_START INTEGER DEFAULT 1,
    CHARSET TEXT,
    DIRECTION TEXT DEFAULT 'Y',
    SHORT_DATE_FORMAT TEXT DEFAULT 'n/j/Y',
    MEDIUM_DATE_FORMAT TEXT DEFAULT 'M j, Y',
    LONG_DATE_FORMAT TEXT DEFAULT 'F j, Y',
    FULL_DATE_FORMAT TEXT DEFAULT 'l, F j, Y',
    DAY_MONTH_FORMAT TEXT DEFAULT 'F j',
    DAY_SHORT_MONTH_FORMAT TEXT DEFAULT 'M j',
    DAY_OF_WEEK_MONTH_FORMAT TEXT DEFAULT 'l, F j',
    SHORT_DAY_OF_WEEK_MONTH_FORMAT TEXT DEFAULT 'D, F j',
    SHORT_DAY_OF_WEEK_SHORT_MONTH_FORMAT TEXT DEFAULT 'D, M j',
    SHORT_TIME_FORMAT TEXT DEFAULT 'g:i a',
    LONG_TIME_FORMAT TEXT DEFAULT 'g:i:s a',
    AM_VALUE TEXT DEFAULT 'am',
    PM_VALUE TEXT DEFAULT 'pm',
    NUMBER_THOUSANDS_SEPARATOR TEXT DEFAULT ',',
    NUMBER_DECIMAL_SEPARATOR TEXT DEFAULT '.',
    NUMBER_DECIMALS INTEGER DEFAULT 2
);

INSERT OR IGNORE INTO b_culture (ID, CODE, NAME, FORMAT_DATE, FORMAT_DATETIME, FORMAT_NAME, CHARSET)
VALUES (1, 'ru', 'Russian', 'DD.MM.YYYY', 'DD.MM.YYYY HH:MI:SS', '#NAME# #LAST_NAME#', 'UTF-8');

CREATE TABLE IF NOT EXISTS b_language (
    LID TEXT NOT NULL PRIMARY KEY,
    SORT INTEGER NOT NULL DEFAULT 100,
    DEF TEXT NOT NULL DEFAULT 'N',
    ACTIVE TEXT NOT NULL DEFAULT 'Y',
    NAME TEXT,
    FORMAT_DATE TEXT,
    FORMAT_DATETIME TEXT,
    FORMAT_NAME TEXT,
    CHARSET TEXT,
    DIRECTION TEXT,
    CULTURE_ID INTEGER,
    CODE TEXT
);

INSERT OR IGNORE INTO b_language (LID, SORT, DEF, ACTIVE, NAME, FORMAT_DATE, FORMAT_DATETIME, CHARSET, DIRECTION, CULTURE_ID, CODE)
VALUES ('ru', 1, 'Y', 'Y', 'Russian', 'DD.MM.YYYY', 'DD.MM.YYYY HH:MI:SS', 'UTF-8', 'Y', 1, 'ru');

CREATE TABLE IF NOT EXISTS b_site (
    LID TEXT NOT NULL PRIMARY KEY,
    SORT INTEGER NOT NULL DEFAULT 100,
    DEF TEXT NOT NULL DEFAULT 'N',
    ACTIVE TEXT NOT NULL DEFAULT 'Y',
    NAME TEXT,
    DIR TEXT,
    LANGUAGE_ID TEXT,
    DOC_ROOT TEXT,
    SERVER_NAME TEXT,
    EMAIL TEXT,
    CHARSET TEXT
);

INSERT OR IGNORE INTO b_site (LID, SORT, DEF, ACTIVE, NAME, DIR, LANGUAGE_ID, DOC_ROOT, SERVER_NAME, CHARSET)
VALUES ('s1', 1, 'Y', 'Y', 'Test', '/', 'ru', '', 'localhost', 'UTF-8');

CREATE TABLE IF NOT EXISTS b_site_lang (
    LID TEXT NOT NULL,
    SITE_ID TEXT NOT NULL,
    SORT INTEGER NOT NULL DEFAULT 100,
    PRIMARY KEY (LID, SITE_ID)
);

INSERT OR IGNORE INTO b_site_lang (LID, SITE_ID) VALUES ('ru', 's1');

CREATE TABLE IF NOT EXISTS b_user (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TIMESTAMP_X TIMESTAMP NULL,
    LOGIN TEXT,
    PASSWORD TEXT,
    CHECKWORD TEXT,
    ACTIVE TEXT NOT NULL DEFAULT 'Y',
    NAME TEXT,
    LAST_NAME TEXT,
    EMAIL TEXT,
    DATE_REGISTER TIMESTAMP NULL,
    LID TEXT
);

INSERT OR IGNORE INTO b_user (ID, LOGIN, PASSWORD, ACTIVE, DATE_REGISTER, LID)
VALUES (1, 'admin', '', 'Y', datetime('now'), 's1');

CREATE TABLE IF NOT EXISTS b_group (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TIMESTAMP_X TIMESTAMP NULL,
    ACTIVE TEXT NOT NULL DEFAULT 'Y',
    C_SORT INTEGER DEFAULT 100,
    ANONYMOUS TEXT NOT NULL DEFAULT 'N',
    NAME TEXT,
    DESCRIPTION TEXT
);

INSERT OR IGNORE INTO b_group (ID, ACTIVE, C_SORT, ANONYMOUS, NAME) VALUES (1, 'Y', 1, 'Y', 'All users');
INSERT OR IGNORE INTO b_group (ID, ACTIVE, C_SORT, ANONYMOUS, NAME) VALUES (2, 'Y', 2, 'N', 'Administrators');

CREATE TABLE IF NOT EXISTS b_event_log (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TIMESTAMP_X TIMESTAMP NULL,
    SEVERITY TEXT,
    AUDIT_TYPE_ID TEXT,
    MODULE_ID TEXT,
    ITEM_ID TEXT,
    REMOTE_ADDR TEXT,
    USER_AGENT TEXT,
    REQUEST_URI TEXT,
    SITE_ID TEXT,
    USER_ID INTEGER,
    GUEST_ID INTEGER,
    DESCRIPTION TEXT
);
