-- Seed data and iblock tables for integration tests (SQLite).

UPDATE b_module SET DATE_ACTIVE = datetime('now') WHERE ID = 'main';
INSERT OR IGNORE INTO b_module (ID, DATE_ACTIVE) VALUES ('iblock', datetime('now'));
UPDATE b_module SET DATE_ACTIVE = datetime('now') WHERE ID = 'iblock';

INSERT OR IGNORE INTO b_option (MODULE_ID, NAME, VALUE, SITE_ID) VALUES ('main', '~crypto_b_salt', 'test_salt', '');
INSERT OR IGNORE INTO b_option (MODULE_ID, NAME, VALUE, SITE_ID) VALUES ('iblock', 'version', '1', '');

CREATE TABLE IF NOT EXISTS b_iblock_type (
    ID TEXT NOT NULL PRIMARY KEY,
    SECTIONS TEXT DEFAULT 'Y',
    EDIT_FILE_BEFORE TEXT,
    EDIT_FILE_AFTER TEXT,
    IN_RSS TEXT DEFAULT 'N',
    SORT INTEGER DEFAULT 500
);

INSERT OR IGNORE INTO b_iblock_type (ID, SECTIONS, SORT) VALUES ('content', 'Y', 100);

CREATE TABLE IF NOT EXISTS b_iblock_type_lang (
    IBLOCK_TYPE_ID TEXT NOT NULL,
    LID TEXT NOT NULL,
    NAME TEXT,
    SECTIONS_NAME TEXT,
    ELEMENTS_NAME TEXT,
    PRIMARY KEY (IBLOCK_TYPE_ID, LID)
);

INSERT OR IGNORE INTO b_iblock_type_lang (IBLOCK_TYPE_ID, LID, NAME, SECTIONS_NAME, ELEMENTS_NAME)
VALUES ('content', 'ru', 'Контент', 'Разделы', 'Элементы');

CREATE TABLE IF NOT EXISTS b_iblock (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TIMESTAMP_X TEXT,
    IBLOCK_TYPE_ID TEXT NOT NULL,
    LID TEXT DEFAULT 's1',
    CODE TEXT,
    NAME TEXT NOT NULL,
    ACTIVE TEXT DEFAULT 'Y',
    SORT INTEGER DEFAULT 500,
    LIST_PAGE_URL TEXT,
    DETAIL_PAGE_URL TEXT,
    SECTION_PAGE_URL TEXT,
    VERSION INTEGER DEFAULT 2,
    INDEX_ELEMENT TEXT DEFAULT 'N',
    INDEX_SECTION TEXT DEFAULT 'N',
    WORKFLOW TEXT DEFAULT 'N',
    BIZPROC TEXT DEFAULT 'N'
);

INSERT OR IGNORE INTO b_iblock (
    ID, TIMESTAMP_X, IBLOCK_TYPE_ID, LID, CODE, NAME, ACTIVE, SORT, VERSION
) VALUES (
    1, datetime('now'), 'content', 's1', 'test_iblock', 'Тестовый инфоблок', 'Y', 100, 2
);

CREATE TABLE IF NOT EXISTS b_iblock_site (
    IBLOCK_ID INTEGER NOT NULL,
    SITE_ID TEXT NOT NULL,
    PRIMARY KEY (IBLOCK_ID, SITE_ID)
);

INSERT OR IGNORE INTO b_iblock_site (IBLOCK_ID, SITE_ID) VALUES (1, 's1');

CREATE TABLE IF NOT EXISTS b_iblock_section (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TIMESTAMP_X TEXT NOT NULL,
    MODIFIED_BY INTEGER,
    DATE_CREATE TEXT,
    CREATED_BY INTEGER,
    IBLOCK_ID INTEGER NOT NULL,
    IBLOCK_SECTION_ID INTEGER,
    ACTIVE TEXT DEFAULT 'Y',
    GLOBAL_ACTIVE TEXT DEFAULT 'Y',
    SORT INTEGER DEFAULT 500,
    NAME TEXT NOT NULL,
    PICTURE INTEGER,
    LEFT_MARGIN INTEGER DEFAULT 1,
    RIGHT_MARGIN INTEGER DEFAULT 2,
    DEPTH_LEVEL INTEGER DEFAULT 1,
    DESCRIPTION TEXT,
    DESCRIPTION_TYPE TEXT DEFAULT 'text',
    CODE TEXT,
    XML_ID TEXT,
    TMP_ID TEXT
);

INSERT OR IGNORE INTO b_iblock_section (
    ID, TIMESTAMP_X, IBLOCK_ID, IBLOCK_SECTION_ID, ACTIVE, GLOBAL_ACTIVE, SORT, NAME,
    LEFT_MARGIN, RIGHT_MARGIN, DEPTH_LEVEL, CODE, XML_ID
) VALUES (
    1, datetime('now'), 1, NULL, 'Y', 'Y', 100, 'Корневой раздел', 1, 4, 1, 'root', 'sec-root'
);

INSERT OR IGNORE INTO b_iblock_section (
    ID, TIMESTAMP_X, IBLOCK_ID, IBLOCK_SECTION_ID, ACTIVE, GLOBAL_ACTIVE, SORT, NAME,
    LEFT_MARGIN, RIGHT_MARGIN, DEPTH_LEVEL, CODE, XML_ID
) VALUES (
    2, datetime('now'), 1, 1, 'Y', 'Y', 200, 'Дочерний раздел', 2, 3, 2, 'child', 'sec-child'
);

CREATE TABLE IF NOT EXISTS b_iblock_element (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TIMESTAMP_X TEXT,
    MODIFIED_BY INTEGER,
    DATE_CREATE TEXT,
    CREATED_BY INTEGER,
    IBLOCK_ID INTEGER NOT NULL,
    IBLOCK_SECTION_ID INTEGER,
    ACTIVE TEXT DEFAULT 'Y',
    ACTIVE_FROM TEXT,
    ACTIVE_TO TEXT,
    SORT INTEGER DEFAULT 500,
    NAME TEXT NOT NULL,
    PREVIEW_PICTURE INTEGER,
    PREVIEW_TEXT TEXT,
    PREVIEW_TEXT_TYPE TEXT DEFAULT 'text',
    DETAIL_PICTURE INTEGER,
    DETAIL_TEXT TEXT,
    DETAIL_TEXT_TYPE TEXT DEFAULT 'text',
    CODE TEXT,
    XML_ID TEXT,
    WF_STATUS_ID INTEGER,
    SHOW_COUNTER INTEGER DEFAULT 0
);

INSERT OR IGNORE INTO b_iblock_element (
    ID, TIMESTAMP_X, DATE_CREATE, IBLOCK_ID, IBLOCK_SECTION_ID, ACTIVE, SORT, NAME, CODE, XML_ID
) VALUES (
    1, datetime('now'), datetime('now'), 1, 1, 'Y', 100, 'Тестовый элемент', 'test-element', 'el-1'
);

INSERT OR IGNORE INTO b_iblock_element (
    ID, TIMESTAMP_X, DATE_CREATE, IBLOCK_ID, IBLOCK_SECTION_ID, ACTIVE, SORT, NAME, CODE, XML_ID
) VALUES (
    2, datetime('now'), datetime('now'), 1, 2, 'Y', 200, 'Элемент в подразделе', 'nested-element', 'el-2'
);
