<?php

declare(strict_types=1);

namespace MB\BitrixTest\Database\Dump;

use PDO;

final class SqliteDumper
{
    public function dump(PDO $pdo, string $outputPath, ?SqliteDumpOptions $options = null): void
    {
        $options = $options ?? new SqliteDumpOptions();

        $lines = [];
        $lines[] = '-- Generated by SqliteDumper';
        $lines[] = 'PRAGMA foreign_keys=OFF;';
        $lines[] = 'BEGIN TRANSACTION;';

        if ($options->includeSchema) {
            $schemaRows = $pdo->query(
                "SELECT type, name, tbl_name, sql
                 FROM sqlite_master
                 WHERE sql IS NOT NULL
                   AND name NOT LIKE 'sqlite_%'
                 ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'index' THEN 1 WHEN 'trigger' THEN 2 ELSE 3 END, name"
            )->fetchAll(PDO::FETCH_ASSOC);

            foreach ($schemaRows as $row) {
                $sql = trim((string) $row['sql']);
                if ($sql === '') {
                    continue;
                }
                $lines[] = $sql . ';';
            }
        }

        if ($options->includeData) {
            $tables = $pdo->query(
                "SELECT name
                 FROM sqlite_master
                 WHERE type='table'
                   AND name NOT LIKE 'sqlite_%'
                 ORDER BY name"
            )->fetchAll(PDO::FETCH_COLUMN);

            foreach ($tables as $tableName) {
                $quotedTable = '"' . str_replace('"', '""', (string) $tableName) . '"';
                $rows = $pdo->query('SELECT * FROM ' . $quotedTable)->fetchAll(PDO::FETCH_ASSOC);
                foreach ($rows as $row) {
                    $columns = array_map(
                        static fn (string $column): string => '"' . str_replace('"', '""', $column) . '"',
                        array_keys($row)
                    );
                    $values = array_map(static fn (mixed $value): string => self::sqliteValue($value), array_values($row));
                    $lines[] = 'INSERT INTO ' . $quotedTable . ' (' . implode(', ', $columns) . ') VALUES (' . implode(', ', $values) . ');';
                }
            }
        }

        $lines[] = 'COMMIT;';

        $dir = dirname($outputPath);
        if (!is_dir($dir)) {
            mkdir($dir, 0777, true);
        }

        file_put_contents($outputPath, implode(PHP_EOL, $lines) . PHP_EOL);
    }

    public static function sqliteValue(mixed $value): string
    {
        if ($value === null) {
            return 'NULL';
        }
        if (is_int($value) || is_float($value)) {
            return (string) $value;
        }

        return "'" . str_replace("'", "''", (string) $value) . "'";
    }
}
